In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

回傳 arr 中 index 為 8 的值。

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

和 python list 的 slicing 一樣，但不包含終值，也就是不包含 index 5。

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

從 index 0 開始選，選到 index 5，不包含 index 6。

In [8]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

從 index 5 開始選到最後。

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

將選起來的值都變成 100。

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

代表抓取全部的值。

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

如果將值取代了，不管是原本（arr）還是（slice_of_arr）都會變成新的值。在 NumPy 裡面，不是 copy array，而是取代掉，因為可以節省記憶體空間。

In [20]:
arr_copy = arr.copy()

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:] = 100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

和上面的不同，如果不想取代掉原本陣列裡的值，而是想要複製後再取代，則要用 copy() 方法來達成。

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]

5

In [29]:
arr_2d[1][1]

25

如果是要抓取二維陣列裡的值，則需要輸入行列的 index，第一個 [] 是行，第二個 [] 是列。

In [30]:
arr_2d[1,1]

25

不用兩個 [][]也可以，在單一個 [] 裡面輸入 <code>x,x</code>即可，第一個 x 代表行的 index，第二個 x 代表列的 index。

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

第一個是行，所以是從頭抓取到 index 1，就會抓 5,10,15,20,25,30。

第二個是列，所以是從 index 1 抓取全部，最後就會抓到 10,15,25,30。

In [32]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 5

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

將陣列裡的每個值和 5 比較，如果有 > 5 就會回傳 True，如果 < 5 就會回傳 False，也可以將結果陣列指定給其他變數。

In [38]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

可以用這樣的方式，來做陣列的選取，用 arr[bool_arr] 就只會回傳是 True 的結果。

In [39]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

可以直接將 In[35] 到 In[38] 合併為一行。

In [40]:
arr [arr < 3]

array([1, 2])