#### 判斷陣列維度的方法：
1. 如果在回傳 array() 裡面，只有一對 [] 則代表是一維陣列。
2. 如果再回傳 array() 裡面，有兩對 [[]] 則代表是二維陣列。

#### arange 和 linspace 的差別在：
1. arange() 裡的參數為，起始值、終值和增值。
2. linspace() 裡的參數為，起始值、終值和出現多少個數。

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

將最原始的 list 轉變成 NumPy 中的 array。

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

將原始的多個 list 轉變成 NumPy 中的 二維陣列。

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange() 是直接將數值轉變成陣列。

在 () 內，第一個數字是起始值為 0 ，第二個數字是終值為 10，但跟 python 的 range 相同，都不包含終值。

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

第三個數字為增值， step 的意思。

In [9]:
np.zeros(3)

array([0., 0., 0.])

建立特殊陣列，其在陣列裡面的值皆為 0。

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

如果在原本的 () 裡面再加上 ()，則代表會變成二維陣列。

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

第一個數字代表的是行的數量為 2，第二個數字代表的是列的數量為 3。

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

linspace：可以建立等差數列，從 0 開始到 5，出現 10 個數字。因為預設 endpoint 為 True ，所以一定會出現終值，如果 endpoint 設定為 False，則不會出現終值。

In [15]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.eye(1)

array([[1.]])

eye：建立對角矩陣，在 () 內的數字，代表會出現幾行幾列，且行跟列的數量皆會相同，同時在對角線的部分，皆為1。

In [21]:
np.random.rand(5)

array([0.37690068, 0.15510129, 0.2056316 , 0.86970008, 0.70594762])

random.rand：建立亂數矩陣，如果在 () 內的數字只有一個，代表是一維陣列，在陣列裡就會出現幾個數，出現數字的值都會在 0-1 之間。

In [22]:
np.random.rand(5,5)

array([[0.24572025, 0.60046531, 0.04109808, 0.42832128, 0.25134914],
       [0.26352421, 0.09374741, 0.58618351, 0.16673419, 0.73357413],
       [0.67247634, 0.89675746, 0.0041361 , 0.9945018 , 0.12810882],
       [0.35092352, 0.67776809, 0.30791927, 0.78559976, 0.20405617],
       [0.19863835, 0.90177617, 0.54119582, 0.93099461, 0.26311974]])

如果在 () 內的數字只有兩個，代表是二維陣列，在陣列裡會出現幾行幾列，出現數字的值都會在 0-1 之間。

In [23]:
np.random.randn(2)

array([2.00170846, 1.19282165])

建立常態分配的陣列，在 () 內的數字為一個，代表是一維陣列，在陣列裡就會出現多少個數字。

In [24]:
np.random.randn(4,4)

array([[-0.04147733,  0.09001539,  0.39367608,  0.39446074],
       [-1.25184152,  1.68180318, -1.04428916,  0.66885843],
       [ 1.26609832, -0.761588  , -1.24730356,  0.47961911],
       [ 1.40291209, -0.25938736,  1.05945287, -1.00691601]])

建立常態分配的陣列，在 () 內的數字為兩個，代表是二維陣列，在陣列裡會出現幾行幾列。

In [25]:
np.random.randint(1,100)

9

random.randint：在 () 內，第一個數字為最小值，第二個數字為最大值，且隨機選取一個數字。

In [26]:
np.random.randint(1,100,10)

array([61, 32, 79,  1, 49, 21, 80, 53, 17, 18])

在 () 內，第一個數字為最小值，第二個數字為最大值，第三個數字為要選幾個，其中最小值是被包含在裡面的（inclusive），最大值是不被包含在裡面的（exclusive）。

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([28, 27, 45, 16, 29, 22, 24,  6,  1, 37])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

重新改變陣列的形狀，原本是一維陣列，但用 reshape 可以將陣列改為二維陣列。

In [32]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

但在轉換形狀的過程中，陣列要能被滿足，也就是說在 arr 是只有 25 個數字，所以只能滿足 5x5 的二維陣列，但不能滿足 5x10 的二維陣列，所以就會出現錯誤。

In [33]:
arr1 = np.arange(24)

In [34]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

在 arr1 裡面，只有 24 個數字，要將 arr1 的形狀轉變為 5x5 的二維陣列是可以的，但會自動填滿缺少的部分，所以會發現在二維陣列中，多出一個數字 24。

In [36]:
ranarr

array([28, 27, 45, 16, 29, 22, 24,  6,  1, 37])

In [37]:
ranarr.max()

45

In [38]:
ranarr.min()

1

在建立出來的亂數陣列中，如果要找到最大值，可以用 max() 方法，如果要找到最小值，可以用 min() 方法。

In [39]:
ranarr.argmax()

2

In [40]:
ranarr.argmin()

8

在建立出來的亂數陣列中，如果要找到最大值所在的 index，可以用 argmax() 方法，如果要找到最小值所在的 index，可以用 argmin() 方法。

In [41]:
arr.shape

(25,)

shape：可以得知目前這個陣列的形狀為何，arr 回傳的為 (25,)，因為是一維陣列，所以不會有第二個參數。

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

因為已經將 reshape 後的結果，丟給變數 arr，所以在呼叫一次 arr.shape 就會是二維陣列的狀態。

In [44]:
arr.dtype

dtype('int64')

可以了解陣列的資料型態是什麼。