In [1]:
import numpy as np

#### 1. 建立有10個0的陣列。

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. 建立有10個1的陣列。

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3. 建立有10個5的陣列。

In [4]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 4. 建立一個陣列裡面包含10到50。

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 5. 建立一個陣列範圍從10到50，但只包含偶數。

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 6. 建立一個3x3的二維陣列，裡頭包含0到8。

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. 建立一個3x3的對角二維陣列。

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. 從0到1中，隨機挑選一個值。

In [9]:
np.random.rand(1)

array([0.33882348])

#### 9. 建立一個二維常態分配陣列，裡頭包含25個值。

In [10]:
np.random.randn(25)

array([ 1.78506255, -0.74532707,  1.95145579,  0.76533276, -0.90651012,
        0.88039766, -0.78235175, -0.68019637,  0.79603985,  0.90997916,
       -0.68962711, -1.93416687, -0.43613976, -0.55032962,  0.93246717,
        2.70197421, -1.37487782,  0.65185424, -1.25318894,  0.37708061,
       -0.54100797,  0.34237492,  0.65319129,  0.20920814, -0.35917139])

#### 10. 建立一個二維陣列，包含的值從 0.01到1。

In [11]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 11. 建立一個線性陣列，裡頭的值從0到1，且有25個。

In [12]:
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

#### 12. 從以下的陣列找到相對應的值：

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. 找到一個陣列裡頭的值包含12到25。

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. 找到在陣列裡的20。

In [15]:
mat[3,4]

20

#### 15. 找到一個陣列裡頭的值包含2,7,12。

In [16]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### 16. 找到一個陣列裡頭的值包含21到25。

In [17]:
mat[4,:]

array([21, 22, 23, 24, 25])

#### 17. 找到一個陣列裡頭的值包含16到25。

In [18]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 18. 將陣列裡面的值全部相加。

In [19]:
mat.sum()

325

#### 19. 計算這個陣列的標準差。

In [20]:
mat.std()

7.211102550927978

#### 20. 找到這個陣列每一欄的總和。

In [21]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])